### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by tlycken** [JuliaMath/Interpolations.jl#140]
When I started this project, in close collaboration with @timholy, I had the opportunity to spend a lot of my coding time with Julia, as I was actively using it myself. For quite some time now, this is no longer the case, and Julia programming has been pushed back on my priority list to the place of "hobbies I can't quite find the time for".

This was fine as long as the packages I maintained were relatively stable, with little activity in issues and pull requests, but lately I've felt that there is more and more going on that I'm unable to keep up with. Thus, I feel I'm no longer doing as well as I'd like as a maintainer, and I think it's time to pass the baton to someone else.

I'm opening this issue as a call for a discussion on where this package should live. Would you like to assume ownership? Do you know of an organization that would?

**Comment by timholy** [comment]
Thanks for having the bravery to admit limits. I struggled with this for a long time with HDF5/JLD before finally deciding that I just couldn't do it anymore. 

Out of curiosity, is your migration away from Julia a decision you came to on your own, or a product of circumstance?

As far as organizations go, perhaps JuliaMath?

**Comment by tlycken** [comment]
It's mostly a matter of circumstances. When I discovered Julia, I was studying for a masters degree in engineering physics, and could choose whatever tools I liked. Julia was a fantastic choice (I'm sure I don't have to convince you about this :D) and I gladly spent the extra time needed to build stuff that didn't exist yet.

Instead of in physics, I ended up as a .NET programmer with no real use case for Julia at work (for now, at least), and with less spare time for hobby projects of this magnitude. And I've become more serious about learning F#, which is more relevant than Julia for work, but competes about the same parts of my spare time.

I'm actually hoping to move my career in a direction where Julia might be a valuable tool again, and in that case I'm expecting to return to being an active member of the community. However, since I have no idea how long that might take, if it ever happens, I think it makes sense to step down meanwhile.

**Comment by tlycken** [comment]
Re: JuliaMath, what's the best way to contact them as an organization? Tag some of the members here? Send an email to somewhere? Post in a discourse group? (It shows that I've been out of the loop for a while...)

**Comment by timholy** [comment]
Seem OK to move this to JuliaMath? CCing the owners: @Aerlinger, @andreasnoack, @ararslan , @JeffBezanson, @jiahao, @mauro3, @simonbyrne, @StefanKarpinski, @stevengj, @tkelman, @ViralBShah.

**Comment by mauro3** [comment]
Bummer!  And thanks for the cool package!

Moving this to JuliaMath would be fine (although not 100% fitting), but that would not really solve the maintainer problem...

**Comment by timholy** [comment]
@mauro3, do you know of a better org?

**Comment by mauro3** [comment]
No.

**Comment by sglyon** [comment]
@tlycken I can _help_ maintain, if we can find one other person willing to sign on as a co-maintainer

Thanks for the work here!

**Comment by ViralBShah** [comment]
While I can't say I can help maintain, we will do our best at Julia Computing to help with the maintenance load on this package. Let's get it to JuliaMath.

**Comment by timholy** [comment]
OK, what's the best approach? Either we can make @tlycken an owner of JuliaMath, or he can grant ownership privileges to someone who is an owner on JuliaMath. In addition to the CC list above, I'm an owner.

**Comment by ViralBShah** [comment]
@timholy Best approach is for you to get the ownership of the package and then you can move it to JuliaMath.

**Comment by timholy** [comment]
You OK with that, @tlycken? Obviously you can keep yourself as an owner, too.

**Comment by ararslan** [comment]
Another +1 for JuliaMath. It sounds like a good fit to me and I'd also be happy to help maintain the package.

**Comment by tlycken** [comment]
Great! I'm now a member of the JuliaMath org.

However, if I transfer ownership of this package to the org, won't package installs etc break? What has to be updated in METADATA.jl? (Is there anyone here that wouldn't mind taking care of all that plumbing for me, once I transfer the repo?)

**Comment by timholy** [comment]
GitHub will forward it automatically, at least for a time. And I'll be happy to handle the changes elsewhere (it's basically updating the badges in the README, and the `url` in METADATA).

**Comment by tlycken** [comment]
It's done!

I'll gladly remain a co-admin of this repository, so that, should I find time in the future, the hoops I need to jump to get back in are as few as possible. But now things like tagging releases, reviewing pull requests and activating tools like attobot won't require waiting for me anymore :)

Thank you, everyone, for being so helpful and supportive.

**Comment by tkelman** [comment]
And you should double-check that all CI services are still / re - enabled

**Comment by sglyon** [comment]
Great!

If you would like me to help maintain the package I will need access to it here in it's new home. Could someone with the right permissions please add me? Thanks!

**Comment by mauro3** [comment]
I sent you an invite.

**Comment by sglyon** [comment]
Great thanks!

**Comment by ararslan** [comment]
Thanks @tlycken for making this awesome package, and thanks to all who've volunteered to continue maintenance so that the package can keep being awesome. And to the new JuliaMath members: welcome. 🙂
