### ISSUE TITLE
Linear() extrapolation with NoInterp() interpolation (question) 

### ISSUE THREAD

**Issue by HugoLhuillier** [JuliaMath/Interpolations.jl#156]
I noted that it is impossible to specify a linear extrapolation to an interpolant that has `NoInterp()` in some dimensions. E.g. 

```julia 
F     = *(collect(1.:10.), collect(1:4)')
itp   = interpolate(F, (BSpline(Linear()), NoInterp()), OnGrid());
itp   = scale(itp, 1:10, 1:4)
itp   = extrapolate(itp, (Linear(), Interpolations.Throw()))
```
Then 
```
julia> itp[10.1., 1]
ERROR: ArgumentError: The length of the provided gradient vector (2) did not match the number of interpolating dimensions (1)
```

I suppose that this is related to the fact that "the wrapped interpolation object must support gradient". Nevertheless, would there be a way to get around this error?

**Comment by timholy** [comment]
Sorry you never got a response. See #189.
