### ISSUE TITLE
Julia 0.6 breaks scaling with LinSpace grid?

### ISSUE THREAD

**Issue by gabrielgggg** [JuliaMath/Interpolations.jl#165]
Hello, all! I upgraded to the latest version and now some code is complaining about my use of `LinSpace`. Am I doing something wrong? The error I get is:

```julia
ERROR: MethodError: no method matching coordlookup(::LinSpace{Float64}, ::Float64)
Closest candidates are:
  coordlookup(::UnitRange, ::Any) at /home/gmihalache/.julia/v0.6/Interpolations/src/scaling/scaling.jl:71
  coordlookup(::StepRange, ::Any) at /home/gmihalache/.julia/v0.6/Interpolations/src/scaling/scaling.jl:73
  coordlookup(::StepRangeLen, ::Any) at /home/gmihalache/.julia/v0.6/Interpolations/src/scaling/scaling.jl:76
Stacktrace:
```
Thank you!

**Comment by sglyon** [comment]
Hi @gabrielgggg could you please post a code snippet you used to construct your interpolation object?

Thank you!

**Comment by gabrielgggg** [comment]
Sure, one of the calls is:

`iV = Interpolations.scale(interpolate(V0, ( BSpline(Cubic(Line())), BSpline(Cubic(Line())) ), OnCell()), gg.y, gg.b)`

where the type of `V0` is `Array{Float64, 2}` and `gg.y`  and `gg.b` are `LinSpace{Float64}`.

BUT!!! This self-contained example works:

```
using Interpolations
V0 = Array{Float64, 2}(5, 6)
yGrid = linspace(-1.0, 1.0, 5)
bGrid = linspace(2.0, 3.0, 6)
iV = Interpolations.scale(interpolate(V0, ( BSpline(Cubic(Line())), BSpline(Cubic(Line())) ), OnCell()), yGrid, bGrid)
```

This seems to be because `linspace` now returns something with type
```
julia> typeof(yGrid)
StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}
```

whereas in my code I was using `LinSpace{Float64}` variables for my grids. I never know what's the idiomatic way to do stuff like this, so any advice is greatly appreciated!

**Comment by gabrielgggg** [comment]
The old code works if I don't explicitly type my grid variables. Alternatively, I could type them using the new `StepRangeLen` type. It's not clear to me what's best practice. I'm sorry if this is not `Interpolations`-specific!

**Comment by sglyon** [comment]
Hey @gabrielgggg you've identified this as not Interpolations.jl specific

[This section](https://github.com/JuliaLang/julia/blame/259996c07e87fc3d2da8f05d4dfa405cdf45fbbe/NEWS.md#L323-L341) of the release notes explains the change and what the new `StepRangeLen` type does.

Given that this is the default behavior going forward, I would recommend that once you are ready to move to Julia 0.6 full time that you use that type instead of `LinSpace` when typing your variables. Then, like you noted above, Interpolations.jl will just work.

**Comment by timholy** [comment]
The implementation for `StepRange` is effectively the same as the implementation for `StepRangeLen` which could also be used for `LinSpace`. No reason we can't support a general `Range` object.
