### ISSUE TITLE
Add documentation for parametric 1D splines embedded on 2D grids

### ISSUE THREAD

**Issue by juliohm** [JuliaMath/Interpolations.jl#166]
First off, thanks for this great package!

I am having difficulty in interpolating a 1D spline embedded on a 2D grid. Suppose I have a 2D Array where some pixels are marked as knots. I can easily interpolate these pixels manually with line segments and get a discretized polyline passing through all of them, however, I need something smooth.

Let's say I have 3 knots in a 100x100 image:

```julia
A = falses(100,100)
A[1,1] = A[30,50] = A[50,30] = A[100,100] = true
```

How can I fit a cubic spline passing through these activated pixels with Interpolations.jl? Ideally I would have a parametrization of the spline with `t in [0,1]` that I could use to find out the index `(i,j)` in the array where the spline is passing through. In the example, `S(0.) = (1,1)` and `S(1.) = (100,100)`.

**Comment by juliohm** [comment]
In other words, does Interpolations.jl support parametric splines? This example in Python is exactly what I am looking for (scroll down in the link to the 4th plot):

https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html#spline-interpolation

**Comment by juliohm** [comment]
Just found a thread explaining how to do it with Interpolations.jl:

http://julia-programming-language.2336112.n4.nabble.com/Parametric-splines-tp37794p37818.html

**Comment by juliohm** [comment]
Could you please document this feature in the README? That would be very helpful to first-time users.

**Comment by sglyon** [comment]
Glad you were able to figure out your issue @juliohm 

More documentation is always great. I don't think I'll be able to get to it myself anytime soon  and I don't totally understand the problem domain. Do you think you'd be up for adding a note to the readme @juliohm ?

**Comment by juliohm** [comment]
Hi @sglyon, I can try add a simple note to the README and reference the author from the link I posted. Currently, I don't fully understand what is happening at the implementation level though. I was more curious about the mathematical model behind it and how one could extend this example to 3D for instance where we fit a trajectory curve embedded in 3D space.

I will play more with the API before I send a PR, thank you.

**Comment by timholy** [comment]
Don't wait too long, though...doc PRs are crucial and they are almost always best from someone who has struggled and then emerged victorious.
