### ISSUE TITLE
Interpolations.jl in Julia 0.6

### ISSUE THREAD

**Issue by cauribeteran** [JuliaMath/Interpolations.jl#168]
Hi. I'm trying to do scaled cubic spline interpolations in Julia v0.6 using Interpolations.jl However, after I build the interpolation object I try to scale it and I get a UndefVarError: scale not defined. Does anyone know if scale was deprecated in Interpolations v.0.6.2 or in Julia v0.6? What the correct syntax instead?

**Comment by sglyon** [comment]
Hmm maybe it conflicts with another function `scale`.

Could you try two things :

1. Try using `Interpolations.scale` using the same functions arguments 
2. If that doesn't solve it then try creating a minimal working example to post here so we can experiment more

**Comment by cauribeteran** [comment]
Thanks sglyon! That was exactly what was happening.
