### ISSUE TITLE
Example  no longer working

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaMath/Interpolations.jl#170]
```
nx = 10
f(x) = sin.(2pi/(nx-1) * (x-1))

xcoarse = 1:nx
ycoarse = f(xcoarse);

xfine = 1:.1:xcoarse[end]
yfine = f(xfine);
 
using Interpolations

yitp = interpolate(ycoarse, BSpline(Linear), OnGrid)
```
from the documentation does not run with  v0.6. 

LoadError: MethodError: Cannot `convert` an object of type Type{Interpolations.Linear} to an object of type Interpolations.BSpline
This may have arisen from a call to the constructor Interpolations.BSpline(...),
since type constructors fall back to convert methods.
while loading C:\Users\PetrKrysl\.julia\v0.6\OtolithMotion\src\OtolithMotion.jl, in expression starting on line 29
in Type at base\sysimg.jl:24

**Comment by sglyon** [comment]
I believe the problem you are missing is you need to have opening and closing parenthesis after `Linear` (as in the README).

This line of code should work

```julia
yitp = interpolate(ycoarse, BSpline(Linear()), OnGrid)
```

The error Julia complained about was that you passed the `BSpline` function the name of the type `Linear` instead of an _instance_ of the type -- `Linear()`

**Comment by PetrKryslUCSD** [comment]
`yitp = interpolate(ycoarse, BSpline(Linear()), OnGrid())` works, and my point was that the documentation was sadly out of whack with the code.

**Comment by timholy** [comment]
Can you be explicit about which documentation is out of date? (On a brief glance, I didn't see this problem in the README.) Or even better, fix it and submit a pull request?

**Comment by PetrKryslUCSD** [comment]
It is in Interpolations.jl/doc/Interpolations.jl.ipynb

I am just getting started with Interpolations. Following the documentation
did not work.
Hence my "issue". When I have gathered some experience,  I will come back
and help
with fixing the documentation.

Regards,

Petr

On Tue, Aug 22, 2017 at 4:00 AM, Tim Holy <notifications@github.com> wrote:

> Can you be explicit about which documentation is out of date? (On a brief
> glance, I didn't see this problem in the README.) Or even better, fix it
> and submit a pull request?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/c0f386373bbcd55532cfc493a6ab1475640b6b53?url=https%3A%2F%2Fgithub.com%2FJuliaMath%2FInterpolations.jl%2Fissues%2F170%23issuecomment-323992743&userId=1197778&signature=57a409e4f212f4a4>,
> or mute the thread
> <https://mailtrack.io/trace/link/994ef3fedbbec5e5cdfe4f3136a4837d9fe06919?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJZjWKz9B-V3c3yOL_IQsWO4NqUcT7JBks5sarTZgaJpZM4O9u0W&userId=1197778&signature=eecfb13d82bdc00c>
> .
>



-- 
Petr Krysl
Professor
University of California, San Diego
9500 Gilman Dr., #0085, La Jolla, CA 92093
Skype: Petr.Krysl.UCSD.EDU
<https://mailtrack.io/trace/link/5964117a953e7d6f8dd1755f15ffc19b19a80dbd?url=http%3A%2F%2FPetr.Krysl.UCSD.EDU&userId=1197778&signature=7bcfddba3a029c41>,
Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/
<https://mailtrack.io/trace/link/1bf2fbace3d19aabaf4bda54168ee0cfeb1bb33b?url=http%3A%2F%2Fhogwarts.ucsd.edu%2F~pkrysl%2F&userId=1197778&signature=1a58b4ddf2d086e4>
