### ISSUE TITLE
Complains about Grid.jl on Windows

### ISSUE THREAD

**Issue by EricForgy** [JuliaMath/Interpolations.jl#174]
![image](https://user-images.githubusercontent.com/8954730/30004062-a03ab1de-90f2-11e7-9ac1-7dc058b7bf90.png)

**Comment by EricForgy** [comment]
I think it has something to do with tests since Grid.jl is not in REQUIRE. I'll see if I can take a shot at fixing it when I get a chance, but wanted to just drop it in here for now.

**Comment by timholy** [comment]
The only place Grid is used here is in `perf/run_shootout.jl`, which shouldn't affect your installation experience at all. I can't imagine the failure here is in Interpolations, it must lie somewhere else. Can you install other packages? What does `Pkg.update()` say?

**Comment by EricForgy** [comment]
Hi Tim 👋 How are you? It's been a long time 😊 

I don't know what happened, but as you can see above, all I do is `Pkg.add("Interpolations")` from a clean REPL and get that error for some reason.

It could possibly have something to do with the fact that when I installed Julia 0.6.0, the first package I tried to add was a private repo that had a dependency on Grid.jl. That kicked off some initialization with METADATA and it complained that Grid.jl is not supported by Julia 0.6.0. So maybe my METADATA did not initialize properly or something?

**Comment by EricForgy** [comment]
You must be right (no surprise). This is not an issue with Interpolations.jl. Thanks :)

![image](https://user-images.githubusercontent.com/8954730/30009482-f6bbbfde-9152-11e7-92b1-83a834e0e2cb.png)
