### ISSUE TITLE
Can we interpolate an arbitrary (odd) number of knots in more than 1 dimension?

### ISSUE THREAD

**Issue by juliohm** [JuliaMath/Interpolations.jl#185]
Is there any way to interpolate a function f(x,y) based on let's say 3 knots in 2D? Suppose I have three knots at (x1,y1), (x2,y2) and (x3,y3), each of which has a corresponding value z1, z2 and z3. How to retrieve a surface passing through these points?

**Comment by sglyon** [comment]
Right now this library only supports tensor product grids, so you would need data for (x1,y1), (x1,y2), (x1,y3), (x2,y1), (x2,y2), (x12y3), (x3,y1), (x3,y2), (x3,y3)

**Comment by juliohm** [comment]
Thank you @sglyon , I wanted to confirm it wasn't possible with the current version of the package.
