### ISSUE TITLE
Periodic boundaries for Linear Interpolation

### ISSUE THREAD

**Issue by natschil** [JuliaMath/Interpolations.jl#201]
It seems like the following does not yet work:

 `Interpolations.interpolate(U,BSpline(Linear(Periodic())),OnGrid())`

Am I getting the syntax wrong, or is there no linear interpolation on periodic grids?

Context: I would like to interpolate some worldwide ocean data, hence I need need linear interpolation (as I have a whole bunch of NaN values where there is land) and periodic boundary conditions in one direction would be nice :)

**Comment by tlycken** [comment]
@natschil It's supposed to work. Can you show a failing example with some sample data you're trying to interpolate?

**Comment by sglyon** [comment]
This is a mathematical issue. 

To filter coefficients for higher order splines we need to specify boundary conditions so there are as many equations as coefficients. 

For Linear B splines you have one coefficient per data point, so no boundary condition is needed (in fact, there is no filtering at all because the coefficients are the data points)

**Comment by tlycken** [comment]
@sglyon Ah, sorry - good catch :)

**Comment by natschil** [comment]
@sglyon : That makes sense. I guess the downside to not allowing it as a parameter to Linear() (despite it doing nothing) is that when switching the type of interpolation (e.g. from Cubic() to Quadratic() to Linear()) one has to also change the syntax in terms of the argument, even though one wants to interpolate the same object with the same boundary conditions (does that make sense)

@tylcken: yes, I was in fact looking for periodic extrapolation, my bad. I'll give that a go instead.

**Comment by natschil** [comment]
@tlycken : Actually now that I think of it, I do need to in some sense do interpolation. The data I'm using is 360-periodic, and has the first entry at 0.125 and last one 359.875, with spacing of 0.25 i.e. the point 0 (=360) is between two points. So I can't simply add an extra point on one side of the grids and make an identification while still working with a regular grid...

**Comment by tlycken** [comment]
@natschil That scenario is actually supported. Consider this (1D) example:

```
using Interpolations, Plots

f(x) = sin(x)
xs = linspace(0, 2pi, 10)[1:end-1] # note that we don't want the overlapping point at 2pi
A = f.(xs);
itp = interpolate(A, BSpline(Linear()), OnGrid()) # interpolate linearly between the data points
stp = scale(itp, xs) # re-scale to the actual domain
etp = extrapolate(stp, Periodic()) # extrapolate periodically

xs_long = linspace(-2pi, 4pi, 100)
A_long = [etp[x] for x in xs_long]
p = plot(xs, A, seriestype=:scatter, label="Data")
plot!(p, xs_long, A_long, label="Extrapolated")
```

![image](https://user-images.githubusercontent.com/1550920/37425327-3f88a464-27c3-11e8-9ed8-86b279655ae1.png)
