### ISSUE TITLE
Deprecation of array indexing calls `[]`

### ISSUE THREAD

**Issue by chiyahn** [JuliaMath/Interpolations.jl#212]
As suggested in https://github.com/JuliaMath/Interpolations.jl/pull/206#issuecomment-405056722, I propose the following procedural changes to deprecate interpolation evaluation by array indexing `[]`:

- [x] Support interpolation evaluation by function calls `()` (complete from https://github.com/JuliaMath/Interpolations.jl/pull/206)
- [x] Modify`README.md` to let users know that `[]` is deprecated in favour of `()` (complete from https://github.com/JuliaMath/Interpolations.jl/pull/206)
- [ ] Start throwing deprecation warnings for evaluation with `[]`
- [ ] Modify unit tests and files in `doc` directory that evaluate interpolation objects by `[]` to `()` 
- [ ] Modify any script in package that evaluates interpolation objects by `[]` to `()`
- [ ] (After tagging a major release) remove `[]` from the code base entirely

The first two steps will be completed as soon as the pull request https://github.com/JuliaMath/Interpolations.jl/pull/206 is approved and changes are committed accordingly. Completing the rest of the procedure should not be a complex task.

**Comment by tlycken** [comment]
Nice! I suggest adding to the to do-list also the following actions:

* [] start throwing depreciation warnings for evaluation with `[]`
* [] (after tagging a major release) remove `[]` from the code base entirely

**Comment by chiyahn** [comment]
No problem, just added them to the list!

**Comment by lstagner** [comment]
Instead of removing `[]` syntax entirely would it be possible to just have it used for accessing the underlying array.
