### ISSUE TITLE
Confused about the true meaning of OnCell and OnGrid

### ISSUE THREAD

**Issue by timholy** [JuliaMath/Interpolations.jl#228]
This may sound surprising, but I'm looking for clarification about what OnCell and OnGrid actually mean. Let's take the case of `Constant`: my interpretation is that `OnCell` *should* mean that the array value is constant over `i-0.5` to `i+0.5` but has a step discontinuity at the edges of this region. Conversely, I would expect `OnGrid` to be constant over `i` to `i+(1-eps())`. In other words, something like this:

![constant-desired](https://user-images.githubusercontent.com/1525481/44526892-ec112d80-a6aa-11e8-9065-c55fb3c6a0ed.png)

But that's not what we have, and indeed `OnGrid` and `OnCell` seem to behave identically:

![constant_real](https://user-images.githubusercontent.com/1525481/44526756-98064900-a6aa-11e8-85a4-b006d517101b.png)

Likewise for Quadratic:

![quadratic](https://user-images.githubusercontent.com/1525481/44526600-229a7880-a6aa-11e8-942e-10581563df27.png)

By the definition I am picturing, I'm not even sure there is an obvious meaning to `Linear`, `OnCell` that is also continuous. (The closest I can come up with is that the slope at `i` is `(y[i+1]-y[i-1])/2`, but that has discontinuities at the half-integers.)

So despite having worked with the package a lot (though not for quite a while, truth be told), I am confused.

**Comment by tlycken** [comment]
I think the original discussion of `OnGrid` vs `OnCell` arose out of needs for handling boundaries on or between the given data points (see e.g. the discussion in #1, as well as https://github.com/JuliaMath/Interpolations.jl/pull/9#issuecomment-64469777 with following comments), with the intent of having the same results on the interior. Thus, I'm not sure it's supposed to make a difference except at the edges.

**Comment by tlycken** [comment]
Re: what it would mean to have `Linear, OnCell` in the interior, I recall drawing a graph with the knots between the data points, which basically looked like an optimization problem: find the series of slopes that create a continuous graph, with as small slope-jumps as possible. I _think_ I also found a way to formulate that problem in terms of linear B-spline coefficients, but I have no idea where I found that, or if I documented it at the time.

**Comment by timholy** [comment]
Thanks for the reminder!

OK, if this really is just about the boundary conditions, I might think about moving this to be more closely attached to the `BC` object. But not the highest priority.
