### ISSUE TITLE
Interpolations.extrapolate gives errors

### ISSUE THREAD

**Issue by Symplectomorphism** [JuliaMath/Interpolations.jl#232]
When I use the Interpolations.extrapolate command, I get the following error:

ERROR: LoadError: MethodError: no method matching zero(::Type{Any})

Here is a sample code to reproduce the problem:

```
A_x = collect(1.0:2.0:40.0)
knots = (A_x,)
itp = interpolate(knots, A, Gridded(Linear()))
extrapolate(itp, Line)
Error showing value of type Interpolations.FilledExtrapolation{Any,1,Interpolations.GriddedInterpolation{Float64,1,Float64,Gridded{Linear},Tuple{Array{Float64,1}}},Gridded{Linear},UnionAll}:
ERROR: MethodError: no method matching zero(::Type{Any})
```

**Comment by timholy** [comment]
Try changing that last line to
```julia
extrapolate(itp, Line())
```
We should probably throw an error for the version you used.

(Did you see this in the docs somewhere?)

**Comment by Symplectomorphism** [comment]
Okay, what you say does work. Thank you very much!

There is no mention of how to call extrapolate in the documentation. I saw it after I typed 

`?extrapolate`

in Julia REPL. It does not mention how to provide the second argument, but I suppose I should have been alerted to it being a function. It might be good to add a simple example in the documentation.

**Comment by timholy** [comment]
After I asked, I noticed that too. Pretty big oversight. I'll fix that at the same time. Thanks for reporting the problems!
