### ISSUE TITLE
gridded extrapolation

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaMath/Interpolations.jl#237]
In Interpolations.jl version 0.8, I could make a extrapolation for a gridded variable:

```julia
using Interpolations
A = rand(20)
A_x = collect(1.0:2.0:40.0)
knots = (A_x,)
itp = interpolate(knots, A, Gridded(Linear()))
itp(-2.0)
```

However, this does not work any more with the new version 0.9.1. A function `extrapolate(knots, A, Gridded(Linear()))` does not seem to be implemented. What would be the recommended upgrade path?

**Comment by timholy** [comment]
Use
```julia
etp = extrapolate(itp, Line())
```
or something. See https://github.com/JuliaMath/Interpolations.jl#extrapolation
