### ISSUE TITLE
Parametric splines example from README broken?

### ISSUE THREAD

**Issue by fasiha** [JuliaMath/Interpolations.jl#253]
The first example in the ["Parametric splines" section](https://github.com/JuliaMath/Interpolations.jl#parametric-splines) of the README doesn't work with freshly-installed Interpolations package:
```
julia> itp = scale(interpolate(A, (BSpline(Cubic(Natural(OnGrid()))), NoInterp())), t, 1:2)
ERROR: MethodError: Cannot `convert` an object of type Interpolations.OnGrid to an object of type Interpolations.Line
This may have arisen from a call to the constructor Interpolations.Line(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] Interpolations.Line(::Interpolations.OnGrid) at ./sysimg.jl:77
```
Forgive me, if I was familiar enough with Interpolations to know how to fix it, I'd submit pull request but I'm just trying to figure out how to use it 🙇‍♂️.

**Comment by timholy** [comment]
Works for me. Can you check what version of Interpolations you're using? You might be stuck on an old version (0.10.3 is current).

**Comment by timholy** [comment]
Since it works for me, closing in the absence of further input.
