### ISSUE TITLE
#256 introduced type instability

### ISSUE THREAD

**Issue by cstjean** [JuliaMath/Interpolations.jl#258]
Thank you very much for the quick fix in #256. It apparently introduced a type instability, MWE:

```julia
using Test, Unitful, Interpolations

function interpolate_1d()
    time = [2017, 2018]
    unit = u"V"
    y = [1.f0, 2.f0] .* unit
    how = Interpolations.Gridded(Interpolations.Linear())
    interp = Interpolations.interpolate((time,), y, how)
    extrap = Interpolations.extrapolate(interp, 1.f0 * unit)
    return extrap
end

ii = interpolate_1d()
@inferred ii(2018)
```

On Julia 1.0.1 with Interpolations v0.10.3, this is type-stable, but it becomes unstable on v0.10.4. If I change `unit` to `1`, then the situation is reversed (0.10.3 unstable, 0.10.4 stable)

**Comment by timholy** [comment]
The responsible block of code has been an inferrability scourge for a long time. This bug report finally tricked my brain into solving it in the obvious way. So, thanks! (See #259)
