### ISSUE TITLE
Flat() Option for extrapolation not recognised

### ISSUE THREAD

**Issue by jfimbett** [JuliaMath/Interpolations.jl#262]
When I try to do a multidimensional interpolation, plus the extrapolation to handle elements outside of the grid I get the following error when using the option Flat()

`V_func = extrapolate(interpolate((v, ls, x), V, Gridded(Linear())), (Flat(),Flat() , Flat()));`

ERROR: UndefVarError: Flat not defined

But this doesnt happen if I use Linear for example

`V_func = extrapolate(interpolate((v, ls, x), V, Gridded(Linear())), (Line(),Line() , Line()));`

Then it works, why is not recognising me Flat() ?

Im running Julia Version 1.0.1 (2018-09-29), and I just updated the Interpolations.jl package

Thank you

**Comment by timholy** [comment]
Works for me. But you didn't show how to create the actual variables you're supplying (`v`, `ls`, `x`, `V`), maybe that's important somehow.

**Comment by jfimbett** [comment]
Thank you, Here is an example of the code

```
using Interpolations

x_grid = collect(range(0, stop=100, length=101))
y_grid = collect(range(0, stop=100, length=101))
z_grid = collect(range(0, stop=100, length=101))

V=rand(size(x_grid,1), size(y_grid,1), size(z_grid,1))

itp=interpolate((x_grid, y_grid, z_grid), V, Gridded(Linear()))
ext = extrapolate(itp, (Flat(),Flat(),Flat()));
```

I get the error: UndefVarError: Flat not defined

But when I run it with the last line like

`ext = extrapolate(itp, (Line(),Line(),Line()));`

It works

**Comment by timholy** [comment]
Works for me. Check the version number of your interpolations package. Also scan for warnings about conflicts with naming in other packages (e.g., "both X and Y export Flat...").

**Comment by jfimbett** [comment]
Thank you very much

I was indeed having a conflict with Flat() from the Optim module, 

Now the problem is solved! Thanks
