### ISSUE TITLE
Gridded Cubic interpolation?

### ISSUE THREAD

**Issue by kkmann** [JuliaMath/Interpolations.jl#265]
Hey,

I wanted to use ForwardDiff on a scaled Cubic BSpline but that does not seem to work since ranges don't work with ForwardDiff. ForwardDiff and gridded linear interpolations work fine - is there any chance of gridded cubic splines coming?

Best,

Kevin

**Comment by tomasaschan** [comment]
@kkmann There's no resistance to adding cubic gridded splines to the package, but the reason they're not there yet is probably that no-one has needed them enough to contribute them.

Adding a new interpolation scheme usually consists of two parts:

1. Someone has to work out the mathematics behind the scheme; how to find the interpolated value, how to handle boundary conditions etc
2. Someone has to implement that description in code.

Obviously, those two don't have to be done by the same person, but both are a non-trivial amount of work. I don't know that any of the active developers of the package have a need for this right now, but if you want to try out a mathematical description and/or an implementation yourself, a PR would be most welcome :)

**Comment by kkmann** [comment]
Thank's for the quick answer! I must correct myself though - ForwardDiff works seamlessly with CubicSplineInterpolation(). For my purposes this is probably enough and I do not really feel up to the job of implementing cubic interpolation on arbitrary pivot points in all generality. 

Thanks for the great work so far!
