### ISSUE TITLE
Issue with show() in 3D scaled interpolations

### ISSUE THREAD

**Issue by natschil** [JuliaMath/Interpolations.jl#270]
The following throws an error in `show()`, even though (as far as I can tell) the interpolation object gets constructed correctly

```
using Interpolations
scale(interpolate(zeros(10,10,10),BSpline(Cubic(Free(OnGrid())))),2:11,2:11,2:11)
```

It works in 2D, and if the scaling ranges are 1:10.

**Comment by timholy** [comment]
Duplicate of #260.
