### ISSUE TITLE
Boundary behavior of gradient and hessian

### ISSUE THREAD

**Issue by dkarrasch** [JuliaMath/Interpolations.jl#272]
This is an observation made in #269. Consider this
```
using Interpolations, Plots
xs = range(-pi, stop=pi, length=100)
f = sin
itp = interpolate(f.(xs), (BSpline(Cubic(Periodic(OnGrid())))))
sitp = scale(itp, xs)
df = x -> Interpolations.gradient(sitp, x)[1]
d2f = x -> Interpolations.hessian(sitp, x)[1]
plot(range(-pi, stop=pi, length=200), f, label="f")
plot!(range(-pi, stop=pi, length=200), df, label="f'")
plot!(range(-pi, stop=pi, length=200), d2f, label="f''")
```
which yields
![sin](https://user-images.githubusercontent.com/26658441/48798325-b0671d80-ed04-11e8-916c-e3305a660359.png)
The behavior at the "boundaries" is very wild, even though the given data should be interpreted as periodic. But then the gradient and the Hessian should look at the boundaries like they look in the center?

**Comment by tomasaschan** [comment]
Without having looked closer at this, my guess is that you're including one point too many in your domain. For a periodic interpolation between `-pi` and `pi`, you want `[-pi, pi)` or `(-pi, pi]` - i.e. inclusive at one end and exclusive at the other. It seems you're using `[-pi, pi]`, which means your data isn't really periodic, and therefore will produce weird boundary results...

**Comment by dkarrasch** [comment]
Thanks, @tomasaschan. I suspected that, but wasn't sure whether or not to include both boundary points. I just tested it and it looks just perfect! I'll modify the test accordingly in the above mentioned PR.
