### ISSUE TITLE
Very slow compilation time for high-dimensional linear interpolation

### ISSUE THREAD

**Issue by rustinpartow** [JuliaMath/Interpolations.jl#279]
I am trying to use linear interpolation for a function of 12 variables, given an array of values calculated over a small number of irregularly-spaced gridpoints.

Although compilation and evaluation is fast for creation of the interpolation object, the evaluation of the interpolation object is extremely slow (the first time) due to what seems to be a strangely long compilation time. Moreover, the compilation time appears to be 200 times longer than for interpolation of an 8-dimensional function!

Any idea what's going on here?

```julia
using Interpolations, ProfileView
cs =  [1.0,2.0];
grid5 = [ [x1,x2,x3,x4,x5] for x1 in cs, x2 in cs, x3 in cs, x4 in cs, x5 in cs];
grid8 = [ [x1,x2,x3,x4,x5,x6,x7,x8] for x1 in cs, x2 in cs, x3 in cs, x4 in cs, x5 in cs, x6 in cs, x7 in cs, x8 in cs];
grid12 = [ [x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12] for x1 in cs, x2 in cs, x3 in cs, x4 in cs, x5 in cs, x6 in cs, x7 in cs, x8 in cs, x9 in cs, x10 in cs, x11 in cs, x12 in cs ];
itp5 = LinearInterpolation((cs,cs,cs,cs,cs), rand(size(grid5)), extrapolation_bc = Interpolations.Flat()  );
itp8 = LinearInterpolation((cs,cs,cs,cs,cs,cs,cs,cs), rand(size(grid8)), extrapolation_bc = Interpolations.Flat()  );
itp12 = LinearInterpolation((cs,cs,cs,cs,cs,cs,cs,cs,cs,cs,cs,cs), rand(size(grid12)), extrapolation_bc = Interpolations.Flat()  );

tic()
itp5( rand(5)... );
println(toq());
tic();
itp8( rand(8)... );
println(toq());
tic();
itp12( rand(12)...);
println(toq());

### Running a second time
tic()
itp5( rand(5)... );
println(toq());
tic();
itp8( rand(8)... );
println(toq());
tic();
itp12( rand(12)...);
println(toq());

```
Output: 
0.475153012
1.742051196
459.168596112

0.000179626
0.000154051
0.000280119

**Comment by timholy** [comment]
On Julia master (roughly the same as the "nightly" build) it's vastly better:

```julia
using Interpolations
itp5 = interpolate(rand(Float64, ntuple(d->2, 5)), BSpline(Linear()));
itp8 = interpolate(rand(Float64, ntuple(d->2, 8)), BSpline(Linear()));
itp12 = interpolate(rand(Float64, ntuple(d->2, 12)), BSpline(Linear()));

julia> @time itp5((rand(5) .+ 1)...)
  0.224000 seconds (733.00 k allocations: 35.433 MiB, 3.76% gc time)
0.5794625508266742

julia> @time itp8((rand(8) .+ 1)...)
  0.625729 seconds (1.88 M allocations: 67.878 MiB, 3.11% gc time)
0.3983907738962953

julia> @time itp12((rand(12) .+ 1)...)
 14.642835 seconds (29.13 M allocations: 892.558 MiB, 4.83% gc time)
0.5021240612473332
```
and of course on the second call it's very fast.

Now, you expect non-linear scaling: in N dimensions, linear interpolation involves arithmetic on 2^N factors so you expect 12 dimensions to be 16 times worse than 8 dimensions. It's pretty close to that on master. You must be using an older version of Julia?

Also just to make sure you know: `using ProfileView` is only needed if you're examining the results of `@profile`. In this case `ProfileView.view(C=true)` shows that the majority of the compilation time is in LLVM itself, so there's not much that Julia can do to improve it.
