### ISSUE TITLE
Flat BC

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaMath/Interpolations.jl#280]
Flat BC forces the spline to go flat parallel to the "y" axis (dependent variable). How can be forced to go flat parallel to the "x" axis (independent variable).

**Comment by tomasaschan** [comment]
That seems like a bug; the intention behind the flat BC is to be flat parallell to the independent variable (and to all independent variables in ND, so e.g. a function of two variables should end up with a flat surface outside of the domain, if using flat BC in all directions).

Could you post a (runnable) code sample that shows the spline going flat parallell to the y axis?

**Comment by montyvesselinov** [comment]
here it is

```Interpolations.interpolate(collect(1:10), Interpolations.BSpline(Interpolations.Quadratic(Interpolations.Flat())), Interpolations.OnCell()).(collect(9:20))```

I expect this it stay at 10 but it does not.

I like this behaviour. If you want you can keep it but call it `Vertical()` or something.

Also if there is a way to define the location of the BC it will be great. For example, in the case above can i set the BC to be at x=20. For flat, it will be easy by adding a point but for a periodic BC will be tricky.

**Comment by tomasaschan** [comment]
What version of `Interpolations.jl` are you on? That code throws a `BoundsError` on the latest version.

In order to get an object you can use for extrapolation, you need to use `extrapolate`; `interpolate` with BC `Flat` will give you an object that ensures that the interpolant is flat _at_ the boundary, but the behavior _outside_ is undefined.

Also, on the latest version, your code sample shows a deprecation warning. Here's an equivalent sample that doesn't:
```
using Interpolations
itp = interpolate(collect(1:10), BSpline(Quadratic(Flat(OnCell()))))
itp.(collect(9:20))
```
That still throws a `BoundsError`, though. Here's how you make it actually extrapolate:
```
using Interpolations
itp = interpolate(collect(1:10), BSpline(Quadratic(Flat(OnCell()))))
etp = extrapolate(itp, Flat(OnCell())) # Wrap the interpolation object with an extrapolation
etp.(collect(9:20))                    # Evaluate from the extrapolating object
```

**Comment by montyvesselinov** [comment]
- Interpolations                0.8.0
 - julia 0.6.4

**Comment by timholy** [comment]
If you want improvements on julia-0.6 you'll have to contribute them yourself; like most others, this package is now committed to julia 1.x.

**Comment by tomasaschan** [comment]
FWIW, here's a code sample that works on Julia 0.6 with Interpolations 0.8.0.

```
using Interpolations
itp = interpolate(collect(1:10), BSpline(Quadratic(Flat())), OnCell())
etp = extrapolate(itp, Flat())
etp[collect(9:20)]
```
As you can see, you still need to create the extrapolation object, but the structure of the scheme indicator types has changed between that version and the latest.
