### ISSUE TITLE
Linear interpolation returns a Ratios.SimpleRatio instead of a float when one of the knots is provided as an integer

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaMath/Interpolations.jl#297]
Linear interpolation returns a Ratios.SimpleRatio instead of a float when one of the knots is provided as an int:

```julia
julia> using Interpolations

julia> x = [1, 2, 3]
3-element Array{Int64,1}:
 1
 2
 3

julia> y = 2 .* x
3-element Array{Int64,1}:
 2
 4
 6

julia> interp = LinearInterpolation(x, y)
3-element extrapolate(interpolate((::Array{Int64,1},), ::Array{Int64,1}, Gridded(Linear())), Throw()) with element type Float64:
 Ratios.SimpleRatio{Int64}(2, 1)
 Ratios.SimpleRatio{Int64}(4, 1)
 Ratios.SimpleRatio{Int64}(6, 1)

julia> interp(2)
Ratios.SimpleRatio{Int64}(4, 1)

julia> interp(2.)
4.0

julia> interp(2.1)
4.2
```

Maybe I'm wrong, but it seems like `interp(2)` should return a float.

EDIT: I just tried feeding arrays of floats to `LinearInterpolation` and that works as expected.

**Comment by timholy** [comment]
Returning a SimpleRatio allows you to avoid floating-point roundoff when appropriate:

```julia
julia> itp = interpolate(([0,9],), [0, 10], Gridded(Linear()))
2-element interpolate((::Array{Int64,1},), ::Array{Int64,1}, Gridded(Linear())) with element type Float64:
 SimpleRatio{Int64}(0, 81)  
 SimpleRatio{Int64}(810, 81)

julia> itp(3)
SimpleRatio{Int64}(270, 81)

julia> 270//81
10//3

julia> 10/3
3.3333333333333335
```
The latter is obviously approximate, the former is exact. 

Base Julia's Ratio type automatically eliminates common factors, but for reasons of performance SimpleRatio does not.

I don't think this is a bug. If you discover mathematical operations that are missing for SimpleRatio, that's a bug (please file at [Ratios.jl](https://github.com/timholy/Ratios.jl).)

**Comment by CameronBieganek** [comment]
Ok, thanks! Sorry for the noise.
