### ISSUE TITLE
Unsatisfiable requirements detected for package ASTInterpreter2

### ISSUE THREAD

**Issue by drarnau** [JuliaMath/Interpolations.jl#309]
Dear all,

I cannot install this package on my machine. I've tried both for Julia 1.1.0 and Julia 1.0.1:
<pre><font color="#8AE234"><b>Updating</b></font> registry at `~/.julia/registries/General`
<font color="#8AE234"><b>  Updating</b></font> git-repo `https://github.com/JuliaRegistries/General.git`
<font color="#8AE234"><b> Resolving</b></font> package versions...
<font color="#EF2929"><b>ERROR: </b></font><font color="#EF2929">Unsatisfiable requirements detected for package ASTInterpreter2 [e6d88f4b]:</font>
<font color="#EF2929"> ASTInterpreter2 [e6d88f4b] log:</font>
<font color="#EF2929"> ├─possible versions are: 0.1.0-0.1.1 or uninstalled</font>
<font color="#EF2929"> ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.1</font>
<font color="#EF2929"> │ └─Atom [c52e3926] log:</font>
<font color="#EF2929"> │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.2] or uninstalled</font>
<font color="#EF2929"> │   └─restricted to versions 0.7.11 by an explicit requirement, leaving only versions 0.7.11</font>
<font color="#EF2929"> └─restricted by julia compatibility requirements to versions: uninstalled — no versions left</font>
</pre>

Any idea on how to fix it?

**Comment by timholy** [comment]
What led you to file this issue here? I don't see any mention of Interpolations in that error message.

Try removing Atom and ASTInterpreter2, updating your packages and adding back Atom (but not ASTInterpreter2).

**Comment by drarnau** [comment]
Apolgies. I was trying to install the Interpolations package.

**Comment by timholy** [comment]
Ah, now I understand, it just wasn't part of the message so I missed that.

**Comment by drarnau** [comment]
I removed Atom and could install Interpolations. Not possible to install Atom back because of ASTInterpreter2.

<pre><font color="#729FCF"><b>(v1.0) pkg&gt; </b></font>add Atom
<font color="#8AE234"><b> Resolving</b></font> package versions...
<font color="#EF2929"><b>ERROR: </b></font><font color="#EF2929">Unsatisfiable requirements detected for package Atom [c52e3926]:</font>
<font color="#EF2929"> Atom [c52e3926] log:</font>
<font color="#EF2929"> ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.2] or uninstalled</font>
<font color="#EF2929"> ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.2]</font>
<font color="#EF2929"> ├─restricted by compatibility requirements with Juno [e5e0dc1b] to versions: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.12] or uninstalled, leaving only versions: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.12]</font>
<font color="#EF2929"> │ └─Juno [e5e0dc1b] log:</font>
<font color="#EF2929"> │   ├─possible versions are: [0.1.0, 0.2.0-0.2.7, 0.3.0-0.3.2, 0.4.0-0.4.1, 0.5.0-0.5.5, 0.6.0, 0.7.0] or uninstalled</font>
<font color="#EF2929"> │   └─restricted to versions 0.5.3 by an explicit requirement, leaving only versions 0.5.3</font>
<font color="#EF2929"> ├─restricted by julia compatibility requirements to versions: [0.7.0-0.7.15, 0.8.0-0.8.2] or uninstalled, leaving only versions: 0.7.0-0.7.12</font>
<font color="#EF2929"> └─restricted by compatibility requirements with ASTInterpreter2 [e6d88f4b] to versions: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.2, 0.8.0-0.8.2] or uninstalled — no versions left</font>
<font color="#EF2929">   └─ASTInterpreter2 [e6d88f4b] log:</font>
<font color="#EF2929">     ├─possible versions are: 0.1.0-0.1.1 or uninstalled</font>
<font color="#EF2929">     └─restricted by julia compatibility requirements to versions: uninstalled</font>
</pre>

**Comment by mattcbro** [comment]
@drarnau I'm seeing the same problem.  I can not install Atom because of Unsatisfiable requirements.  Is this an open issue?  This is happening to me in Julia 1.2.0.

**Comment by timholy** [comment]
Anytime something tries to install ASTInterpreter2, it's trying to install a *really* old version of Atom.jl.

This has absolutely nothing to do with Interpolations. If you can't easily resolve it by updating your packages, please ask on discourse of consult the Pkg documentation.
