### ISSUE TITLE
References missing

### ISSUE THREAD

**Issue by giadasp** [JuliaMath/Interpolations.jl#321]
Dear developers,
I'm using your package for a research project and I'd like to have some references (articles, papers, books etc...) for the methods you implemented.
Thank you very much.

Giada SP.

**Comment by timholy** [comment]
Hmm. Wikipedia? Seriously, we pretty much calculated everything from scratch. Though the following was very informative: Thévenaz, Philippe, Thierry Blu, and Michael Unser. "Interpolation revisited." IEEE Transactions on medical imaging 19.7 (2000): 739-758.

**Comment by giadasp** [comment]
I understand. I thought you were using more advanced techniques coming from
the recent developments in this research field.
Btw, thank you for that reference. I'll look at it.

Il giorno sab 18 mag 2019, 17:18 Tim Holy <notifications@github.com> ha
scritto:

**Comment by timholy** [comment]
The computational techniques are pretty impressive (and possible in few languages other than Julia), but the mathematics is straightforward.
