### ISSUE TITLE
Previous interpolation

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaMath/Interpolations.jl#328]
Is it possible to include *previous* interpolation like in MATLAB *interp1*

> Previous neighbor interpolation. The interpolated value at a query point is the value at the previous sample grid point.

It should be a minimal change from the already existing *constant* interpolation, which is the equivalent to *nearest* interpolation in MATLAB.

**Comment by tomasaschan** [comment]
As you say, the change in implementation is probably quite trivial, given that we already have the constant (nearest) interpolation down. I think the most difficult part of this is to create a good UI/API for it. If you have any suggestions, do share - either inline in this issue discussion, or in a pull request :)
