### ISSUE TITLE
Add example periodic to documentation?

### ISSUE THREAD

**Issue by briochemc** [JuliaMath/Interpolations.jl#340]
I just stumbled upon issue https://github.com/JuliaMath/Interpolations.jl/issues/326 and realized having a MWE would have helped.

What about adding some examples to the documentation? Updating https://github.com/JuliaMath/Interpolations.jl/issues/201, what about 
```julia
using Interpolations, Plots

f(x) = sin(x)
xs = range(0, 2pi, length=6)
A = f.(xs)
itp = interpolate(A, BSpline(Linear())) # interpolate linearly between the data points
stp = scale(itp, xs) # re-scale to the actual domain
etp = extrapolate(stp, Periodic()) # extrapolate periodically

xs_long = range(-2pi, 4pi, length=2000)
A_long = etp(xs_long)
plot(f, xs_long; label="True sin(x)", xticks=([-2π:2π:4π;],["-2\\pi","0","2\\pi","4\\pi"]))
plot!(xs, A, seriestype=:scatter, label="Data")
plot!(xs_long, A_long, label="Extrapolated")
```

which should give:
![GKSTerm](https://user-images.githubusercontent.com/4486578/69305798-64351d00-0c79-11ea-98ac-a6c515cef64c.png)

**Comment by briochemc** [comment]
Here is another example in 2D that is relevant to globe-like maps with only periodic in the `x` aixs (because I was looking for something like that and I could not find it). MWE:
```julia
f(x,y) = sin(x + 1) * (1 + cos(y))
xs = range(0, 2π, length=11)
ys = range(-π/2, π/2, length=6)
A = f.(xs,ys')

itp = interpolate(A, BSpline(Linear())) # interpolate linearly between the data points
stp = scale(itp, xs, ys) # re-scale to the actual domain
etp = extrapolate(stp, (Periodic(), Throw())) # extrapolate periodically

xs_long = range(-2π, 4π, length=2000)
A_long = etp(xs_long, ys)

p1 = plot(xs_long, ys, A_long'; seriestype=:contourf)
XS = vec([x for x in xs, y in ys])
YS = vec([y for x in xs, y in ys])
plot!(XS, YS, zcolor=vec(A), seriestype=:scatter, label="data")
plot!(xticks=([-2π:2π:4π;], ["-2\\pi","0","2\\pi","4\\pi"]))
plot!(yticks=([-π/2,0.0,π/2], ["-\\pi/2","0","\\pi/2"]))

p2 = plot(xs_long, ys, f.(xs_long',ys); seriestype=:contourf)
plot!(XS, YS, zcolor=vec(A), seriestype=:scatter, label="data")
plot!(xticks=([-2π:2π:4π;], ["-2\\pi","0","2\\pi","4\\pi"]))
plot!(yticks=([-π/2,0.0,π/2], ["-\\pi/2","0","\\pi/2"]))

plot(p1, p2, layout=(2,1))
```
produces (top is interpolated/extrapolated, bottom is true `f`, and markers are the data used by Interpolations.jl):
![GKSTerm](https://user-images.githubusercontent.com/4486578/69307585-2a671500-0c7f-11ea-9037-5ae9f7fd1dd4.png)

Again, I think it would be nice to have a little gallery of examples and add those to the documentation.

**Comment by natschil** [comment]
If I understand your MWE correctly, it simply adds an extra point at 2\pi and copies the data there? My issue (#326) was that (a) this requires redundant data, and (b) cubic interpolation seems to treat boundary values wrong as you need values for from the "other side" not only for "extrapolation" but also for "interpolation" . I was initially also interested in interpolation on globe-like maps, my "fix" was to create a package at https://github.com/CoherentStructures/CopernicusUtils.jl that does trilinear/tricubic periodic interpolation on space-time globe-like maps.

**Comment by Datseris** [comment]
@natschil I am facing similar problems. I want to re-grid climate data from a LonLat grid to a different grid (equal area, typically icosahedral based). Thus, the "periodicity" of the longitude is important. I checked CopernicusUtils.jl , but it has been deprecated in favor of OceanTools.jl. But in the docs of OceanTools.jl I couldn't find this functionality anywhere... :(  Could you please give me a link to the functions you have created for this issue?

**Comment by natschil** [comment]
@Datseris The documentation of OceanTools.jl is currently very poor, fixing this has been on my todo list for a while. I've created an issue there at https://github.com/CoherentStructures/OceanTools.jl/issues/1 , don't hesitate to ask further questions.

**Comment by natschil** [comment]
@Datseris : sorry my last comment wasn't very clear - to clarify: I've written an answer to your specific question at the newly createdOceanTools.jl issue I linked to.

**Comment by jaemolihm** [comment]
In #428, I added an example (https://github.com/JuliaMath/Interpolations.jl/blob/master/docs/src/extrapolation.md#periodic-extrapolation) for periodic extrapolation (that does not require an additional point) so we can close this issue.
