### ISSUE TITLE
NaN when interpolation has repetitive coordinate points

### ISSUE THREAD

**Issue by leventov** [JuliaMath/Interpolations.jl#395]
```julia
itp = interpolate(([0.0,0.0,1.0],), [1.0, 1.0, 2.0], Gridded(Linear()))
itp[0.0] # NaN
```

I think this is unreasonable behaviour. Either the library should explicitly throw an exception "cannot interpolate array with duplicate points", or deduplicate the data, as this is possible in this case because the corresponding values are also repeated.

**Comment by mkitti** [comment]
Is the cost of deduplicating nodes worthwhile to impose on all uses though? Perhaps a distinct interface with some guard rails may be useful.

**Comment by leventov** [comment]
Actual interpolations are much more expensive than skimming through the input arrays sequentially.

**Comment by mkitti** [comment]
I think a check with `allunique` in `check_gridded` should do. We currently check `issorted`, but that is apparently not sufficient. Would you like add a test and submit the PR?

https://github.com/JuliaMath/Interpolations.jl/blob/master/src/gridded/gridded.jl#L51

**Comment by leventov** [comment]
> Would you like add a test and submit the PR?

No, thanks

**Comment by mkitti** [comment]
Fixed in 318ebc8

**Comment by greimel** [comment]
This fix broke my code. 

Please consider declaring such changes as breaking and bump the x in 0.x.y the next time.

**Comment by mkitti** [comment]
Could you give an example on which code this broke? It is not clear to me what might have broken unless you depending on that `NaN`?

**Comment by greimel** [comment]
I have duplicated knots, but never called the value at the knot. (You might say it shouldn't have had duplicate knots in the first place, and you're right. But still, the simulations for my project broke.)
