### ISSUE TITLE
Document `interpolate!`

### ISSUE THREAD

**Issue by nandoconde** [JuliaMath/Interpolations.jl#405]
Hello!

I tried the so-called "in-place" interpolation, `interpolate!`, which supposedly used less memory, and got an error when I tried later to scale back the results with `scale` I got an error. From what I assume, the "in-place" version decreases the size of the used nodes by two in each dimension e.g.:

When trying to interpolate using a matrix `A` as values, with size 5×11, I got error later when I tried to scale back with ranges of length 5 and 11 respectively, because it was expecting ranges of 3 and 9. If this is expected behavior, I guess it should be in the `docs`.

Thanks!

**Comment by mkitti** [comment]
This makes sense. I wonder if there is a bug there somewhere. Pull requests always welcome, especially ones that just improve the documentation.

**Comment by timholy** [comment]
It probably depends on the order of the interpolation. For quadratic & cubic, you have to solve a tridiagonal system. When it's not in place, the padding framework adds an "edge" around it so that you can both match the values and have the chosen boundary conditions; when you're in place you can't add an edge, so you have to sacrifice something.

**Comment by nandoconde** [comment]
Great to know! 

This would be my first time contributing to something in Julia, so I am kind of lost. I guess that the steps are:

1. Branch `master` into my computer
2. Add a docstring to `interpolate!`
3. Push upstream 

And I wouldn’t know how to proceed 😅.

I could try it nonetheless if you kindly tell me how!

**Comment by mkitti** [comment]
The easiest way in Julia is `]dev Interpolations` in the REPL or "using Pkg; Pkg.dev("Interpolations")". This will clone master into your `~/.julia/dev` directory. You can then edit the code there.

When you are ready to submit, you could fork this project, and then push your changes into your fork. You can then create a pull request from your fork. I would be more than happy to help walk you through that in more detail if needed.

**Comment by timholy** [comment]
You can also click on the pencil icon for any of the files in the package.

**Comment by nandoconde** [comment]
I have created the PR! #410

**Comment by mkitti** [comment]
Thanks. Looks there's a start there. I'll comment more on the PR.

**Comment by mkitti** [comment]
I merged #410. We may need to enhance that note in the future, but some docstring is better than none.
