### ISSUE TITLE
syntax error in visual.jl

### ISSUE THREAD

**Issue by bifs** [JuliaMath/Interpolations.jl#406]
https://github.com/JuliaMath/Interpolations.jl/blob/e8165ec2d1859a2e67ba89e8a17b4e321c004410/test/visual.jl#L48

This is in the master branch.

There seems to be a missing parentheses; I'm guessing it should be
```julia
itp2 = extrapolate(interpolate(zg, BSpline(Quadratic(Flat(OnCell())))), Line())
```
i.e., before `, Line())` rather than at the end of the line.

VSCode's linter highlighted the problem and trying to compile the file confirmed it, though both indicated the error was happening at a later line.

The github history seems to indicate the change was made 3 years ago; it seems like a bit of a problem it wasn't caught sooner.  Maybe it's not actually part of the test suite?  Or visual tests can't be run automatically?

**Comment by bifs** [comment]
I meant to file this as @RossBoylan.
But I don't know how to change it.  I'll try to add notifications so I actually see them.

**Comment by mkitti** [comment]
I suspect the visual tests were meant to be inspected by a human. Could you submit the change as a pull request? Just click the pencil while on the master branch:
![image](https://user-images.githubusercontent.com/8062771/109568369-d28ba080-7ab4-11eb-8646-1dad83dd3983.png)

**Comment by RossBoylan** [comment]
Not sure what's going on.  I viewed the file in this repository and clicked the edit icon.  This forked the project and I made the edits in the fork.  The work is noted immediately above, but the number of pull requests in this project is unchanged.

**Comment by mkitti** [comment]
It sounds like you are very close. You just need to click Pull Request after navigating to https://github.com/RossBoylan/Interpolations.jl/tree/patch-1
https://github.com/RossBoylan/Interpolations.jl/tree/patch-2

![image](https://user-images.githubusercontent.com/8062771/109586615-8734ba80-7ad3-11eb-9c32-39a2045aab2e.png)
