### ISSUE TITLE
2D Cubic Spline: wrong results?

### ISSUE THREAD

**Issue by atbug** [JuliaMath/Interpolations.jl#419]
I was trying to interpolate the following matrix
```
-0.04762716049382476	-0.0007871604938287646	0.09069283950617546	0.1254328395061748	0.10496283950617169	-0.012727160493824385	-0.11550716049382714	-0.07324716049382829	-0.035497160493825675
-0.0008171604938240762	-0.035737160493823694	0.015412839506176113	0.08778283950617549	0.09655283950617388	0.027052839506175985	-0.06519716049382396	-0.04165716049382695	0.015402839506172938
0.09069283950617546	0.015392839506169764	-0.07326716049382753	-0.04171716049382468	0.005482839506171899	-0.03861716049382835	-0.07704716049382654	0.005522839506170385	0.08742283950617491
0.1254228395061716	0.08761283950617127	-0.041697160493825436	-0.11549716049382397	-0.06517716049382472	-0.07690716049382473	-0.13049716049382454	-0.03855716049382352	0.09659283950617237
0.10500283950617018	0.0965828395061763	0.005592839506171288	-0.06519716049382396	-0.012797160493825288	0.02699283950617115	-0.03860716049382518	-0.07700716049382805	0.02710283950617054
-0.012747160493823628	0.027072839506175228	-0.03833716049382474	-0.0770971604938282	0.027072839506175228	0.10498283950617093	0.09656283950616995	0.005562839506175976	-0.06501716049382367
-0.11536716049382534	-0.06517716049382472	-0.07706716049382578	-0.1305071604938277	-0.038537160493824274	0.09659283950617237	0.12551283950617176	0.08743283950617098	-0.041697160493825436
-0.07307716049382407	-0.04167716049382619	0.005542839506169628	-0.038537160493824274	-0.07706716049382578	0.005592839506171288	0.08776283950617625	0.09072283950617077	0.015422839506172181
-0.03571716049382445	0.015392839506169764	0.08770283950617141	0.09656283950616995	0.02699283950617115	-0.06515716049382547	-0.04168716049382937	0.015432839506175355	-0.0007671604938295218
```

The script is
```julia
using DelimitedFiles, Interpolations

data = readdlm("data.dat")
f = extrapolate(interpolate(data, BSpline(Cubic(Periodic(OnCell())))), Periodic())
xs = 1:0.1:18
ys = f.(xs, xs)
```

However, plotting `xs` and `ys` shows there is a discontinuity:
![image](https://user-images.githubusercontent.com/8522036/116832997-22561900-ab85-11eb-93f6-f323310ca0d4.png)

Then I decided not to use the `Periodic` boundary condition and repeat the data myself:
```julia
using DelimitedFiles, Interpolations

data = repeat(readdlm("data.dat"), 3, 3)
f = interpolate(data, BSpline(Cubic(Reflect(OnCell()))))
```
but the interpolated results does not coincide with the original value:
```julia
data[7, 4] # -0.1305071604938277
f[7, 4] # -0.08599604938271552
```
 
Are the above two issues bugs or do I have a fundamental misunderstanding of how cubic B-spline works?

**Comment by mkitti** [comment]
Could you elaborate which discontinuity you are referring to? If you mean the one at the boundary, then you need to extend `xs` a bit further for this to seem periodic.

```julia
julia> xs = 1:0.1:19-0.1
1.0:0.1:18.9

julia> ys = f.(xs, xs);

julia> using GR

julia> scatter(xs, ys)

julia> hold(true)
true

julia> plot(xs, ys)


```

![image](https://user-images.githubusercontent.com/8062771/116900985-625de000-ac07-11eb-92c1-9a5bbd0751b3.png)

**Comment by atbug** [comment]
No. I was talking about the sudden jump circled in red. The data don't have such behavior:
![image](https://user-images.githubusercontent.com/8522036/116903048-e5803580-ac09-11eb-9db3-d0281e4cdf76.png)

**Comment by mkitti** [comment]
In the second case, you switched to `Reflect`ing boundary conditions. As far as I can tell, this actually does not appear to be implemented for `Cubic`. So that's one issue. It should at least say it's not implemented.

We probably should just create an error:
```julia
julia> Interpolations.prefiltering_system(::Type{T}, ::Type{TC}, n::Int, degree::Cubic{<:Reflect}) where {T,TC} =
   error("Reflecting boundary conditions are not implemented for Cubic")

julia> f = interpolate(data, BSpline(Cubic(Reflect(OnCell()))))
ERROR: Reflecting boundary conditions are not implemented for Cubic
...
```

If I just use periodic boundary conditions with the repeated data, we get the strange spike in the extrapolated region.

```julia
using DelimitedFiles, Interpolations, GR

data = repeat(readdlm("data.dat"), 3, 3)
f = extrapolate( interpolate(data, BSpline(Cubic(Periodic(OnCell())))), Periodic())
xs = 1:0.1:28-0.1
ys = f.(xs, xs)
plot(xs , ys)
```

![image](https://user-images.githubusercontent.com/8062771/116954086-fdcd7000-ac5c-11eb-8a36-761772cf38a8.png)

Digging into the matter further, it seems there is something off about the `Cubic` implementation. The lower and upper bounds should be the same, but they are not. Compare to the quadratic interpolation.

```julia
julia> cubic_itp = interpolate(data, BSpline(Cubic(Periodic(OnCell()))));

julia> bounds(cubic_itp)
((0.5, 9.5), (0.5, 9.5))

julia> cubic_itp(0.5,1)
-0.03781973402323647

julia> cubic_itp(9.5,1)
-0.046705836964412856

julia> quad_itp = interpolate(data, BSpline(Quadratic(Periodic(OnCell()))));

julia> bounds(quad_itp)
((0.5, 9.5), (0.5, 9.5))

julia> quad_itp(0.5,1)
-0.042057485366921166

julia> quad_itp(9.5,1)
-0.042057485366921166
```

I'm going to to have to dig into the commit history here, but it seems there are some missing implementation details in `Cubic`.

**Comment by mkitti** [comment]
I think I found the problem. There is some special cases in `Interpolations.positions(deg::Cubic, ax, x)` and `Interpolations.floorbounds(x, ax)` that needs to be removed for `Periodic`.

```julia
using DelimitedFiles, Interpolations, GR 

function Interpolations.positions(deg::Cubic{<:Periodic}, ax, x)
    xf = floor(x)
    δx = x - xf
    Interpolations.expand_index(deg, Interpolations.fast_trunc(Int, xf), ax, δx), δx
end

data = readdlm("data.dat")

f = extrapolate(interpolate(data, BSpline(Cubic(Periodic(OnCell())))), Periodic())
xs = 1:0.1:18
ys = f.(xs, xs)
plot(xs, ys)
```
![image](https://user-images.githubusercontent.com/8062771/117033713-a4068d80-acd0-11eb-9319-6033060d020f.png)

```julia
xs = 1:0.1:19
ys = f.(xs, xs)
plot(xs, ys)
```
![image](https://user-images.githubusercontent.com/8062771/117034064-f0ea6400-acd0-11eb-8c8d-087bc020f420.png)

**Comment by atbug** [comment]
Thanks for the fix. 

Maybe also error on `Cubic(Reflect(OnCell()))` as you shown above?
