### ISSUE TITLE
Interpolation of incomplete array

### ISSUE THREAD

**Issue by vajnaivik** [JuliaMath/Interpolations.jl#422]
I have been trying to understand the usage of the library to be able
to fill missing data in an array for a few hours now with no luck.

If I have the following data:
(1, 1, 5)
(3, 3, 15)
Is it possible to create a full 2d array based on these values with this library?

The output I'd like would look something like this:
5     7.5    10
7.5  10     12.5
10   12.5  15

Is this the thing called a non-uniform grid in the documentation?
The documentation has the following for usage: "interpolate((nodes1, nodes2, ...), A, interpmode)"
If so, what are the nodes, how are they created and why is the array needed?

**Comment by vajnaivik** [comment]
Thank you for the quick response!

I can see how this works a bit better now, and I 
also see how the question wasn't clear.

What I meant was that I have a few points that I know the value of.
These points are not necessarily at the ends of the array, but somewhere inside it.
It is probably easier to visualize it in 3D:
![known points](https://user-images.githubusercontent.com/61936589/117649369-b892cc00-b18f-11eb-8ede-586c1371f46c.png)

What I have are the red points at random places inside the region.
What I would need are the values of points inside the whole region interpolated from the known values, something like this:
![Interpolated](https://user-images.githubusercontent.com/61936589/117649921-61412b80-b190-11eb-9233-b7b083afdaff.png)

Is this possible with the library?

**Comment by mkitti** [comment]
See https://github.com/eljungsk/ScatteredInterpolation.jl

**Comment by vajnaivik** [comment]
Ok, thank you for your help!
