### ISSUE TITLE
How to perform multiquadric interpolations using matrix? 

### ISSUE THREAD

**Issue by mdsa3d** [JuliaMath/Interpolations.jl#423]
I am trying to replicate the functionality of scipy rbf with multiquadric radial in julia. 
Python reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.Rbf.html

For example, 
I have the following dataset:
```
a = [1.0 1.0 13.41; 2.0 1.0 8.60; 3.0 1.0 5.76; 4.0 1.0 3.58; 5.0 1.0 4.69; 6.0 1.0 3.72; 7.0 1.0 6.32; 8.0 1.0 5.68]
x_train = a[:, 1]
y_train = a[:, 2]
z_train = a[:, 3]
```
And I would like to create (train) a `rbf` or `interpolate` function using the above dataset and predict the values for the following dataset:
```
x_test = [1.0, 2.28, 2.28, 2.285, 3.57, 4.85, 6.14, 7.42, 8.71, 10.0]
y_test = [1.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, 4.0]
```

May I know what would be the correct syntax to execute this operation?

So far I have tried the following function:
```
itp = interpolate((x_train, y_train), z_train, BSpline(Quadratic(Reflect(OnCell()))))
```
But it throws an error! Please advice.

Thanks in advance!

**Comment by mkitti** [comment]
This might not be the right package for what you are trying to do.

See https://github.com/baggepinnen/BasisFunctionExpansions.jl

**Comment by mkitti** [comment]
https://github.com/SciML/Surrogates.jl

**Comment by mkitti** [comment]
https://eljungsk.github.io/ScatteredInterpolation.jl/stable/methods/#Radial-Basis-Functions-1
