### ISSUE TITLE
Test.detect_ambiguities now already does the setdiff 

### ISSUE THREAD

**Issue by vtjnash** [JuliaMath/Interpolations.jl#431]
This should accelerate tests somewhat, since Test.detect_ambiguities can be expensive, but will now already avoid the duplicate work that was previously performed by setdiff
https://github.com/JuliaMath/Interpolations.jl/blob/cba9daebf9746bad56368e220dc167b94de18320/test/runtests.jl#L6-L11
==>
```julia
Test.detect_ambiguities(Interpolations)
```

**Comment by johnnychen94** [comment]
FYI, A perhaps enhanced version of a similar meta quality check is using [Aqua](https://github.com/JuliaTesting/Aqua.jl)

**Comment by mkitti** [comment]
I'm not sure if I follow. Is this what you mean https://github.com/JuliaMath/Interpolations.jl/pull/455/commits/eff8d120f05b71c58ee03af49353202aadc731ef , @vtjnash ?
