### ISSUE TITLE
Interpolations v0.14?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaMath/Interpolations.jl#433]
It looks like the JSoC project https://github.com/SomTambe/DiffImages.jl requests the new AD support to continue the work. Here I kindly request a new release for #414.

Since it drops Julia 1.0 support, a minor version bump is required.

cc: @SomTambe

**Comment by mkitti** [comment]
Is a minor version bump required? Last time I explored that matter, I was convinced it was not. Julia 1.0 users would simply pick up the last compatible Interpolations v0.14 version. I would be happy to be convinced otherwise.

**Comment by johnnychen94** [comment]
Well. "julia" is perhaps one special case where you want to notify users that there's something big happening in this version.

**Comment by mkitti** [comment]
Reviewing #414 , the issue appears to be mainly with testing. I don't know why I did not think about this earlier, but perhaps we should just make the test conditional on the Julia version. Features that currently work on Julia 1.0.x will continue to work.

**Comment by johnnychen94** [comment]
FWIW, patches like https://github.com/JuliaTesting/ReferenceTests.jl/blob/cda66cf74f68118bfacf5bd9069af89269374f83/.github/workflows/UnitTest.yml#L42-L54 help Pkg to resolve the versions correctly in Julia 1.0

**Comment by mkitti** [comment]
As of c5bd734b9b3ffdb88a939539582f0c39b681b455, we have tests passing on Julia 1.0 through nightly. Expect v0.13.3

**Comment by johnnychen94** [comment]
Thanks!

**Comment by DhairyaLGandhi** [comment]
Did the issue mentioned in #414 get resolved?

**Comment by mkitti** [comment]
Yes, CI is passing. I'm not sure if ChainRules works on Julia 1.0, but I'm not sure if it is expected to. For Julia 1.0, we just skip those tests.
