### ISSUE TITLE
Documentation link not up to date

### ISSUE THREAD

**Issue by judober** [JuliaMath/Interpolations.jl#437]
It seems that the documentation linked on github is not the newest. It lacks the newly added monotonic interpolation in control section.

**Comment by dkarrasch** [comment]
Yes, I think the documentation step got lost in 43d19e0a4dc8e7749fddf5827b9afc878e43c556.

**Comment by mkitti** [comment]
I believe that section is now available:
http://juliamath.github.io/Interpolations.jl/latest/control/#Monotonic-interpolation

Please reopen if this is incorrect.
