### ISSUE TITLE
No method matching interpolate(::Vector{Float64}})

### ISSUE THREAD

**Issue by troyrock** [JuliaMath/Interpolations.jl#440]
I'm still a newbie in Julia and I'm having trouble giving interpolate numbers in a form that works:

I have a 2D array of functions and their values generated from a Gaussian Random Field that I would like to do a numerical anti-derivative.  The functions are smooth so I thought giving ODEProblem the interpolate function would do what I want but I'm stuck in "no method matching" land:
```
using Stheno
l = 0.2  # GRF parameter (see table 1)
m = 100  # Number of sensors (see table 1)
initial_condition = 0  # s(0) = 0
train_trajectories = 100  # number of functions with s
x_begin = 0.0
x_end = 1.0
x = range(x_begin, x_end; length=m)
GRF = GP(SEKernel() ∘ ScaleTransform(1/l))
u_train = transpose(rand(GRF(x, 1e-12), train_trajectories))
s_train = similar(u_train)
using Interpolations
using DifferentialEquations
for index in 1:train_trajectories
    problem = ODEProblem(interpolate(u_train[index, :]), initial_condition, (x_begin, x_end))
    s_train[index] = solve(problem, reltol=1e-9, abstol=1e-9)
end
```
I'm getting the error: **MethodError: no method matching interpolate(::Vector{Float64})**

**Comment by johnnychen94** [comment]
You need to tell `interpolate` which interpolation method you're going to apply, e.g., `interpolate(u_train[index, :], BSpline(Linear()))` for 1-order B-Spline interpolation.

**Comment by mkitti** [comment]
Please see `LinearInterpolation` as documented here:
http://juliamath.github.io/Interpolations.jl/latest/convenience-construction/#Convenience-notation-1

```julia
julia> itp = LinearInterpolation(1:3, Float64[4, 5.5, 6])
3-element extrapolate(scale(interpolate(::Vector{Float64}, BSpline(Linear())), (1:3,)), Throw()) with element type Float64:
 4.0
 5.5
 6.0

julia> itp(1.5)
4.75
```

**Comment by mkitti** [comment]
Perhaps we could do

```julia
julia> import Interpolations: LinearInterpolation

julia> LinearInterpolation(v::AbstractVector) = LinearInterpolation(eachindex(v), v)
LinearInterpolation (generic function with 5 methods)

julia> itp = LinearInterpolation([4, 4.5, 5])
3-element extrapolate(scale(interpolate(::Vector{Float64}, BSpline(Linear())), (Base.OneTo(3),)), Throw()) with element type Float64:
 4.0
 4.5
 5.0

julia> itp(2)
4.5

julia> itp(2.5)
4.75
```

**Comment by troyrock** [comment]
I found my error, I was trying to pass it to a function that was expecting it to have 3 arguments (but of course it only has one).  Thanks for your help.

**Comment by mkitti** [comment]
Technically `interpolate` will take anywhere between and two and five arguments. You can list them by doing `methods(interpolate)`.

I highly recommend taking advantage of the community resources listed at https://julialang.org/community/ . The Slack and Zulip #helpdesk channels could address questions like this more efficiently.

**Comment by troyrock** [comment]
Thank you very much, I am actually using Slack and that is where this
question was actually answered.  I appreciate your patience with me while I
learn.
