### ISSUE TITLE
Type instability in hessian when interpolating a 3D field

### ISSUE THREAD

**Issue by touste** [JuliaMath/Interpolations.jl#469]
Hi, see the following MWE:

```
using Interpolations
nx = 5
A = rand(Float64, nx, nx, nx) * 100
itp = interpolate(A, BSpline(Quadratic(Reflect(OnCell()))))
@code_warntype Interpolations.hessian(itp, 1., 1., 1.)
```

This gives a type instability on the `wis` variable:
`wis::Tuple{Tuple{Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}}, Tuple{Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}}, Tuple{Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}}, Tuple{Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}}, Tuple{Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}, Interpolations.WeightedAdjIndex{3, Float64}}, Vararg{Any}}`

This in turn leads to a return type `Any` for the function.

**Comment by mkitti** [comment]
See https://github.com/JuliaLang/julia/issues/43368

**Comment by touste** [comment]
Are you sure this is related? I see the same issue in 1.6.4 and 1.5.4

**Comment by touste** [comment]
That was fast! Thank you very much for fixing this.

**Comment by N5N3** [comment]
Well, the above fix seems only work for 3d case. Some more effort is needed.
