### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by briochemc** [JuliaMath/Interpolations.jl#485]
Current Readme and docs start with 

> NEWS v0.9 was a breaking release. See the [news](http://juliamath.github.io/Interpolations.jl/latest/NEWS/) for details on how to update.

when the current version is 0.13 at the time of submitting this issue. Since there would have been 4 breaking versions since v0.9 (at least), I think it might be time to remove this "NEWS" item! :)

**Comment by briochemc** [comment]
v0.14 makes it 5! Time to update the ReadMe, no?

**Comment by mkitti** [comment]
Oh, I forgot to push that commit.

**Comment by mkitti** [comment]
See #499
