### ISSUE TITLE
Deprecated convenience constructors don't accept keyword arguments

### ISSUE THREAD

**Issue by danielmatz** [JuliaMath/Interpolations.jl#507]
The deprecated camel case convenience constructors (see #501) don't accept keyword arguments. It seems that `@deprecate` only passes along positional arguments by default. I think this can be fixed by doing:

```julia
@deprecate LinearInterpolation(args...; kwargs...) linear_interpolation(args...; kwargs...)
```

**Comment by mkitti** [comment]
Oh that's a problem, ok fixing.

**Comment by mkitti** [comment]
@danielmatz can you confirm that the issue is resolved at version 0.14.3?

**Comment by danielmatz** [comment]
@mkitti Looks good! Thanks!

**Comment by mkitti** [comment]
Thank you for the report.
