### ISSUE TITLE
Manual misses Previous and Next for Constant interpolation

### ISSUE THREAD

**Issue by judober** [JuliaMath/Interpolations.jl#511]
It seems the features from #338 are not mentioned in the manual.

**Comment by mkitti** [comment]
Good point. Would you like to help write something for this?

**Comment by mkitti** [comment]
The first step would be to add docstrings here:

https://github.com/JuliaMath/Interpolations.jl/blob/master/src/b-splines/constant.jl#L4

**Comment by judober** [comment]
I can try to write something

**Comment by mkitti** [comment]
Great. Thank you. If you can submit a pull request, please do. Otherwise, feel free to leave the text here, and I'll integrate it.

**Comment by mkitti** [comment]
cc: @ValentinKaisermayer
