### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by Shmuley95** [JuliaMath/Interpolations.jl#519]
https://juliamath.github.io/Interpolations.jl/latest/control/#Monotonic-interpolation

Maybe I don't understand the documentation, but in the example on monotonic interpolation, in the third line the data and the grid seem to be reversed. That is:
`itp_cdf = extrapolate(interpolate(y, percentile_values, SteffenMonotonicInterpolation()), Flat());`
should probably be
`itp_cdf = extrapolate(interpolate(percentile_values, y, SteffenMonotonicInterpolation()), Flat());`

**Comment by mkitti** [comment]
The documentation looks correct to me. We're trying to estimate the cumulative distribution function.

![image](https://user-images.githubusercontent.com/8062771/190854545-e5bedad7-3c2a-4885-8520-6dcdfaacda94.png)

**Comment by Shmuley95** [comment]
Ah yes, I got a bit confused by the grid over which is interpolated (the x-axis) being named "y" and being described in the comment as "data". My bad!
