### ISSUE TITLE
Is there a way to interpolate over a points cloud using irregular grids?

### ISSUE THREAD

**Issue by mvanzulli** [JuliaMath/Interpolations.jl#552]
This is a minimal problem:

```julia
# Function to be interpolated
f(x,y) = 2 * x * y
# Points where the info is given
points = [(0.,0.), (.25,.5), (.75,0.9), (1.,0.25)]
# field at each point
f_measured = [f(p...) for p in points]
# point to interpolate
point_to_interpolate = (.5,.4) 
```

![Screenshot from 2023-05-20 16-45-55](https://github.com/JuliaMath/Interpolations.jl/assets/50339940/c4bccd21-cc3c-4bb3-8675-1d6fa516b62d)

Is there a way to build an `itp` object ? I tried with irregular equispaced grid but is not the case. 

Txs in advance

**Comment by mkitti** [comment]
Try https://eljungsk.github.io/ScatteredInterpolation.jl/dev/

**Comment by mvanzulli** [comment]
Thank you!
