### ISSUE TITLE
NaturalNeighbours.jl

### ISSUE THREAD

**Issue by DanielVandH** [JuliaMath/Interpolations.jl#560]
Could [NaturalNeighbours.jl](https://github.com/DanielVandH/NaturalNeighbours.jl) be listed as a related package? This package is for scattered (spatial) interpolation in the plane using natural neighbours methods. 

(I would've done the PR myself, but from "If you would like to list a registered package that is related to interpolation, please create a Github issue." I assume you want an issue first.)

**Comment by mkitti** [comment]
Create the pull request please
