### ISSUE TITLE
Interpolate a set of points

### ISSUE THREAD

**Issue by Mehgugs** [JuliaMath/Interpolations.jl#565]
I have a discrete set of points as supplied as `Vector{Float64}`s and would like to interpolate between the points... it's not clear from the documentation how to use this package to do so.

I have: 

```jl
x = [1148.824818, 2312.309814, 2798.761158, 3804.982432, 4577.973609, 5597.522316, 6530.442702, 7616.62858, 7996.460452]
y = [1947.529304, 1979.653498, 2037.209347, 1936.821239, 1703.920827, 1350.554686, 973.0953978, 377.4592877, 105.2281538]
```

and I want to get a cubic spline interpolator.

**Comment by mkitti** [comment]
For irregular 1D sampling like this, try [DataInterpolations.jl](https://github.com/SciML/DataInterpolations.jl).

```julia
julia> import DataInterpolations, Plots

julia> itp = DataInterpolations.CubicSpline(y,x);

julia> Plots.plot(itp)
```

![image](https://github.com/JuliaMath/Interpolations.jl/assets/8062771/00976d49-9025-486a-b74c-1822573a694b)
