### ISSUE TITLE
 MethodError: no method matching Interpolations.Cubic()

### ISSUE THREAD

**Issue by andreasvarga** [JuliaMath/Interpolations.jl#593]
I performed recently the tests for the [PeriodicSystems.jl](https://github.com/andreasvarga/PeriodicSystems.jl) package using Julia 10.2 on Linux (see [here](https://github.com/andreasvarga/PeriodicSystems.jl/actions/runs/8773505699/job/24073666159)). The loaded version of the `Interpolations.jl` package is apparently v0.14 and the following error occurs under Linux:
```

MethodError: no method matching Interpolations.Cubic()
  
  Closest candidates are:
    Interpolations.Cubic(::BC) where BC<:Interpolations.BoundaryCondition
     @ Interpolations ~/.julia/packages/Interpolations/USkTk/src/b-splines/cubic.jl:2 
```
The offending line looks like

`scale(interpolate(vec, BSpline(Cubic())), ts) `

Running the same tests locally under Windows, the version  v0.15.1 is (apparently) used and there is no error. 

I wonder if the difference in the employed versions could explain this behaviour.

**Comment by mkitti** [comment]
`Cubic()` with no parameters was introduced in version `0.14.7`. You are using version `0.14.0`.

**Comment by mkitti** [comment]
See https://github.com/andreasvarga/PeriodicSystems.jl/pull/19

**Comment by andreasvarga** [comment]
Thanks. I will restrict even further to use only version v0.15 and Julia starting with v1.9.
